set_property IOSTANDARD LVCMOS33 [get_ports {a_out_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports {stopRewind_in_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {stepDone_out_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports {doStep_in_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {doRewind_in_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_out_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_out_V[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_out_V[0]}]
set_property PACKAGE_PIN AB11 [get_ports {a_out_V[0]}]
set_property PACKAGE_PIN T22 [get_ports {stepDone_out_V[0]}]
set_property PACKAGE_PIN M15 [get_ports reset_rtl]
set_property PACKAGE_PIN R16 [get_ports {doRewind_in_V[0]}]
set_property PACKAGE_PIN T18 [get_ports {doStep_in_V[0]}]
set_property PACKAGE_PIN P16 [get_ports {stopRewind_in_V[0]}]
set_property DONT_TOUCH true [get_cells design_1_i]
set_property DONT_TOUCH true [get_cells design_1_i/proc_sys_reset_0]
set_property DONT_TOUCH true [get_cells design_1_i/stepperMotor_0]
set_property DONT_TOUCH true [get_cells design_1_i/xlconstant_0]
set_property DONT_TOUCH true [get_cells design_1_i/xlconstant_1]
set_property PACKAGE_PIN Y9 [get_ports sys_clock]


set_property PACKAGE_PIN AB10 [get_ports {b_out_V[0]}]

set_property DONT_TOUCH true [get_cells design_1_i/MUX_32_0]
set_property DONT_TOUCH true [get_cells design_1_i/xlconstant_2]
set_property IOSTANDARD LVCMOS33 [get_ports SEL]
set_property PACKAGE_PIN F22 [get_ports SEL]

set_property IOSTANDARD LVCMOS33 [get_ports {full_step_in_V[0]}]
set_property PACKAGE_PIN H17 [get_ports {full_step_in_V[0]}]


set_property PACKAGE_PIN AA8 [get_ports {d_out_V[0]}]
set_property PACKAGE_PIN AB9 [get_ports {c_out_V[0]}]
