# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-8352-asus/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/xlconstant_v1_1/36911fd5/xlconstant.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/stepperMotor_v1_0/54525cd5/hdl/vhdl/stepperMotor.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_stepperMotor_0_3/synth/design_1_stepperMotor_0_3.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/synth/design_1_proc_sys_reset_0_0.vhd
      C:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/hdl/design_1.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/MUX_32_v1_0/f9cd04c1/MUX_32.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_MUX_32_0_0/synth/design_1_MUX_32_0_0.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_1_1/sim/design_1_xlconstant_1_1.vhd
      C:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0 c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/lib_cdc_v1_0/d3fab4a1/hdl/src/vhdl/cdc_sync.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0 {
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/7820e39a/hdl/src/vhdl/upcnt_n.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/7820e39a/hdl/src/vhdl/sequence.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/7820e39a/hdl/src/vhdl/lpf.vhd
      c:/Users/utente/Desktop/StepperMotorControlSchematic/StepperMotorControlSchematic.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/7820e39a/hdl/src/vhdl/proc_sys_reset.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-8352-asus/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
