-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stepperMotor is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    doStep_in_V : IN STD_LOGIC_VECTOR (0 downto 0);
    doRewind_in_V : IN STD_LOGIC_VECTOR (0 downto 0);
    stopRewind_in_V : IN STD_LOGIC_VECTOR (0 downto 0);
    nSteps_in : IN STD_LOGIC_VECTOR (31 downto 0);
    delayDuration_in : IN STD_LOGIC_VECTOR (31 downto 0);
    full_step_in_V : IN STD_LOGIC_VECTOR (0 downto 0);
    a_out_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    b_out_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    c_out_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    d_out_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    stepDone_out_V : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of stepperMotor is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "stepperMotor,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.299500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=72,HLS_SYN_LUT=322}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";

    signal steps_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal curState : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal prevState : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal counter_delay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sequence_no_V : STD_LOGIC_VECTOR (2 downto 0) := "001";
    signal counter_delay_tmp_0_i_phi_fu_178_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_34 : BOOLEAN;
    signal tmp_cast_fu_243_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal counter_delay_tmp_1_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_phi_fu_188_p6 : STD_LOGIC_VECTOR (2 downto 0);
    signal doRewind_in_V_read_read_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_390_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_10_phi_fu_199_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_341_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_cast_fu_409_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal brmerge_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal doStep_in_V_read_read_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge_i1_fu_283_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge_i_cast_fu_350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_315_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_309_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp_fu_321_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_v_cast_cast_fu_382_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_235_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_7_fu_403_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal doRewind_in_V_not_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_85 : BOOLEAN;
    signal ap_sig_bdd_67 : BOOLEAN;
    signal ap_sig_bdd_57 : BOOLEAN;
    signal ap_sig_bdd_103 : BOOLEAN;


begin




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- counter_delay assign process. --
    counter_delay_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                counter_delay <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3))) then 
                    counter_delay <= counter_delay_tmp_0_i_phi_fu_178_p4;
                end if; 
            end if;
        end if;
    end process;


    -- curState assign process. --
    curState_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                curState <= ap_const_lv2_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0) and not((ap_const_lv1_0 = brmerge_fu_431_p2)) and not((ap_const_lv1_0 = doStep_in_V_read_read_fu_124_p2)) and not((ap_const_lv1_0 = tmp_6_fu_437_p2)))) then 
                    curState <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and not((ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0) and (ap_const_lv1_0 = brmerge_fu_431_p2)))) then 
                    curState <= ap_const_lv2_2;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and not((ap_const_lv1_0 = tmp_4_fu_370_p2)))) then 
                    curState <= ap_const_lv2_3;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and (ap_const_lv1_0 = tmp_4_fu_370_p2))) then 
                    curState <= ap_const_lv2_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_2))) then 
                    curState <= storemerge_i_cast_fu_350_p3;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3) and not((tmp_3_fu_271_p2 = ap_const_lv1_0)))) then 
                    curState <= storemerge_i1_fu_283_p3;
                end if; 
            end if;
        end if;
    end process;


    -- prevState assign process. --
    prevState_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                prevState <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0) and not((ap_const_lv1_0 = brmerge_fu_431_p2)) and not((ap_const_lv1_0 = doStep_in_V_read_read_fu_124_p2)) and not((ap_const_lv1_0 = tmp_6_fu_437_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0) and (ap_const_lv1_0 = brmerge_fu_431_p2)))) then 
                    prevState <= ap_const_lv2_0;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and not((ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and (ap_const_lv1_0 = tmp_4_fu_370_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and not((ap_const_lv1_0 = tmp_4_fu_370_p2))))) then 
                    prevState <= ap_const_lv2_1;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_2))) then 
                    prevState <= ap_const_lv2_2;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3) and not((tmp_3_fu_271_p2 = ap_const_lv1_0)))) then 
                    prevState <= ap_const_lv2_3;
                end if; 
            end if;
        end if;
    end process;


    -- sequence_no_V assign process. --
    sequence_no_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sequence_no_V <= ap_const_lv3_1;
            else
                if ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
                    sequence_no_V <= tmp_10_phi_fu_199_p10;
                end if; 
            end if;
        end if;
    end process;


    -- steps_count assign process. --
    steps_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                steps_count <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then
                    if (ap_sig_bdd_103) then 
                        steps_count <= nSteps_in;
                    elsif (ap_sig_bdd_57) then 
                        steps_count <= ap_const_lv32_0;
                    elsif (ap_sig_bdd_67) then 
                        steps_count <= tmp_7_cast_fu_409_p1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    -- a_out_V assign process. --
    a_out_V_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_11_fu_455_p2, tmp_12_fu_461_p2, tmp_13_fu_467_p2, tmp_14_fu_473_p2, tmp_15_fu_479_p2, tmp_16_fu_485_p2, tmp_17_fu_491_p2, tmp_18_fu_497_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and not((ap_const_lv1_0 = tmp_17_fu_491_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and not((ap_const_lv1_0 = tmp_16_fu_485_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and not((ap_const_lv1_0 = tmp_15_fu_479_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and not((ap_const_lv1_0 = tmp_14_fu_473_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and not((ap_const_lv1_0 = tmp_13_fu_467_p2))))) then 
            a_out_V <= ap_const_lv1_0;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and (ap_const_lv1_0 = tmp_17_fu_491_p2) and not((ap_const_lv1_0 = tmp_18_fu_497_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and not((ap_const_lv1_0 = tmp_12_fu_461_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_11_fu_455_p2))))) then 
            a_out_V <= ap_const_lv1_1;
        else 
            a_out_V <= "X";
        end if; 
    end process;


    -- ap_sig_bdd_103 assign process. --
    ap_sig_bdd_103_assign_proc : process(tmp_cast_fu_243_p1, brmerge_fu_431_p2, doStep_in_V_read_read_fu_124_p2, tmp_6_fu_437_p2)
    begin
                ap_sig_bdd_103 <= ((tmp_cast_fu_243_p1 = ap_const_lv3_0) and not((ap_const_lv1_0 = brmerge_fu_431_p2)) and not((ap_const_lv1_0 = doStep_in_V_read_read_fu_124_p2)) and not((ap_const_lv1_0 = tmp_6_fu_437_p2)));
    end process;


    -- ap_sig_bdd_34 assign process. --
    ap_sig_bdd_34_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_34 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_57 assign process. --
    ap_sig_bdd_57_assign_proc : process(tmp_cast_fu_243_p1, doRewind_in_V_read_read_fu_118_p2)
    begin
                ap_sig_bdd_57 <= ((ap_const_lv3_1 = tmp_cast_fu_243_p1) and not((ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2)));
    end process;


    -- ap_sig_bdd_67 assign process. --
    ap_sig_bdd_67_assign_proc : process(tmp_cast_fu_243_p1, doRewind_in_V_read_read_fu_118_p2, tmp_4_fu_370_p2)
    begin
                ap_sig_bdd_67 <= ((ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and not((ap_const_lv1_0 = tmp_4_fu_370_p2)));
    end process;


    -- ap_sig_bdd_85 assign process. --
    ap_sig_bdd_85_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_cast_fu_243_p1)
    begin
                ap_sig_bdd_85 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3));
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_34)
    begin
        if (ap_sig_bdd_34) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- b_out_V assign process. --
    b_out_V_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_11_fu_455_p2, tmp_12_fu_461_p2, tmp_13_fu_467_p2, tmp_14_fu_473_p2, tmp_15_fu_479_p2, tmp_16_fu_485_p2, tmp_17_fu_491_p2, tmp_18_fu_497_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and not((ap_const_lv1_0 = tmp_14_fu_473_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and not((ap_const_lv1_0 = tmp_13_fu_467_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and not((ap_const_lv1_0 = tmp_12_fu_461_p2))))) then 
            b_out_V <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and (ap_const_lv1_0 = tmp_17_fu_491_p2) and not((ap_const_lv1_0 = tmp_18_fu_497_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and not((ap_const_lv1_0 = tmp_17_fu_491_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and not((ap_const_lv1_0 = tmp_16_fu_485_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and not((ap_const_lv1_0 = tmp_15_fu_479_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_11_fu_455_p2))))) then 
            b_out_V <= ap_const_lv1_0;
        else 
            b_out_V <= "X";
        end if; 
    end process;

    brmerge_fu_431_p2 <= (stopRewind_in_V or doRewind_in_V_not_fu_425_p2);

    -- c_out_V assign process. --
    c_out_V_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_11_fu_455_p2, tmp_12_fu_461_p2, tmp_13_fu_467_p2, tmp_14_fu_473_p2, tmp_15_fu_479_p2, tmp_16_fu_485_p2, tmp_17_fu_491_p2, tmp_18_fu_497_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and not((ap_const_lv1_0 = tmp_16_fu_485_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and not((ap_const_lv1_0 = tmp_15_fu_479_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and not((ap_const_lv1_0 = tmp_14_fu_473_p2))))) then 
            c_out_V <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and (ap_const_lv1_0 = tmp_17_fu_491_p2) and not((ap_const_lv1_0 = tmp_18_fu_497_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and not((ap_const_lv1_0 = tmp_17_fu_491_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and not((ap_const_lv1_0 = tmp_13_fu_467_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and not((ap_const_lv1_0 = tmp_12_fu_461_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_11_fu_455_p2))))) then 
            c_out_V <= ap_const_lv1_0;
        else 
            c_out_V <= "X";
        end if; 
    end process;


    -- counter_delay_tmp_0_i_phi_fu_178_p4 assign process. --
    counter_delay_tmp_0_i_phi_fu_178_p4_assign_proc : process(tmp_3_fu_271_p2, counter_delay_tmp_1_fu_264_p2, ap_sig_bdd_85)
    begin
        if (ap_sig_bdd_85) then
            if ((tmp_3_fu_271_p2 = ap_const_lv1_0)) then 
                counter_delay_tmp_0_i_phi_fu_178_p4 <= counter_delay_tmp_1_fu_264_p2;
            elsif (not((tmp_3_fu_271_p2 = ap_const_lv1_0))) then 
                counter_delay_tmp_0_i_phi_fu_178_p4 <= ap_const_lv32_0;
            else 
                counter_delay_tmp_0_i_phi_fu_178_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            counter_delay_tmp_0_i_phi_fu_178_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    counter_delay_tmp_1_fu_264_p2 <= std_logic_vector(unsigned(counter_delay) + unsigned(ap_const_lv32_1));

    -- d_out_V assign process. --
    d_out_V_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_11_fu_455_p2, tmp_12_fu_461_p2, tmp_13_fu_467_p2, tmp_14_fu_473_p2, tmp_15_fu_479_p2, tmp_16_fu_485_p2, tmp_17_fu_491_p2, tmp_18_fu_497_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and not((ap_const_lv1_0 = tmp_15_fu_479_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and not((ap_const_lv1_0 = tmp_14_fu_473_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and not((ap_const_lv1_0 = tmp_13_fu_467_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and not((ap_const_lv1_0 = tmp_12_fu_461_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_const_lv1_0 = tmp_11_fu_455_p2))))) then 
            d_out_V <= ap_const_lv1_0;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and (ap_const_lv1_0 = tmp_17_fu_491_p2) and not((ap_const_lv1_0 = tmp_18_fu_497_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and (ap_const_lv1_0 = tmp_16_fu_485_p2) and not((ap_const_lv1_0 = tmp_17_fu_491_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv1_0 = tmp_11_fu_455_p2) and (ap_const_lv1_0 = tmp_12_fu_461_p2) and (ap_const_lv1_0 = tmp_13_fu_467_p2) and (ap_const_lv1_0 = tmp_14_fu_473_p2) and (ap_const_lv1_0 = tmp_15_fu_479_p2) and not((ap_const_lv1_0 = tmp_16_fu_485_p2))))) then 
            d_out_V <= ap_const_lv1_1;
        else 
            d_out_V <= "X";
        end if; 
    end process;

    doRewind_in_V_not_fu_425_p2 <= (doRewind_in_V xor ap_const_lv1_1);
    doRewind_in_V_read_read_fu_118_p2 <= doRewind_in_V;
    doStep_in_V_read_read_fu_124_p2 <= doStep_in_V;
    sel_tmp1_fu_329_p2 <= (stopRewind_in_V xor ap_const_lv1_1);
    sel_tmp2_fu_335_p2 <= (full_step_in_V and sel_tmp1_fu_329_p2);
    sel_tmp_fu_321_p3 <= 
        sequence_no_V when (stopRewind_in_V(0) = '1') else 
        tmp_2_fu_315_p2;

    -- stepDone_out_V assign process. --
    stepDone_out_V_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, tmp_cast_fu_243_p1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0))) then 
            stepDone_out_V <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1)))) then 
            stepDone_out_V <= ap_const_lv1_0;
        else 
            stepDone_out_V <= "X";
        end if; 
    end process;

    storemerge_i1_fu_283_p3 <= 
        ap_const_lv2_2 when (tmp_5_fu_277_p2(0) = '1') else 
        ap_const_lv2_1;
    storemerge_i_cast_fu_350_p3 <= 
        ap_const_lv2_3 when (sel_tmp1_fu_329_p2(0) = '1') else 
        ap_const_lv2_0;

    -- tmp_10_phi_fu_199_p10 assign process. --
    tmp_10_phi_fu_199_p10_assign_proc : process(sequence_no_V, ap_sig_cseq_ST_st1_fsm_0, tmp_cast_fu_243_p1, tmp_8_phi_fu_188_p6, tmp_9_fu_341_p3)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1))) then 
            tmp_10_phi_fu_199_p10 <= tmp_8_phi_fu_188_p6;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_2))) then 
            tmp_10_phi_fu_199_p10 <= tmp_9_fu_341_p3;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_cast_fu_243_p1 = ap_const_lv3_3)) and not((tmp_cast_fu_243_p1 = ap_const_lv3_2)) and not((ap_const_lv3_1 = tmp_cast_fu_243_p1)) and not((tmp_cast_fu_243_p1 = ap_const_lv3_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_3)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_cast_fu_243_p1 = ap_const_lv3_0)))) then 
            tmp_10_phi_fu_199_p10 <= sequence_no_V;
        else 
            tmp_10_phi_fu_199_p10 <= "XXX";
        end if; 
    end process;

    tmp_11_fu_455_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_0) else "0";
    tmp_12_fu_461_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_1) else "0";
    tmp_13_fu_467_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_2) else "0";
    tmp_13_v_cast_cast_fu_382_p3 <= 
        ap_const_lv3_2 when (full_step_in_V(0) = '1') else 
        ap_const_lv3_1;
    tmp_14_fu_473_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_3) else "0";
    tmp_15_fu_479_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_4) else "0";
    tmp_16_fu_485_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_5) else "0";
    tmp_17_fu_491_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_6) else "0";
    tmp_18_fu_497_p2 <= "1" when (tmp_10_phi_fu_199_p10 = ap_const_lv3_7) else "0";
    tmp_1_fu_309_p2 <= std_logic_vector(unsigned(sequence_no_V) + unsigned(ap_const_lv3_6));
    tmp_2_fu_315_p2 <= std_logic_vector(unsigned(sequence_no_V) + unsigned(ap_const_lv3_7));
    tmp_3_fu_271_p2 <= "1" when (counter_delay_tmp_1_fu_264_p2 = delayDuration_in) else "0";
    tmp_4_fu_370_p2 <= "1" when (signed(steps_count) > signed(ap_const_lv32_0)) else "0";
    tmp_5_fu_277_p2 <= "1" when (prevState = ap_const_lv2_2) else "0";
    tmp_6_fu_437_p2 <= "1" when (signed(nSteps_in) > signed(ap_const_lv32_0)) else "0";
    tmp_7_cast_fu_409_p1 <= std_logic_vector(resize(unsigned(tmp_7_fu_403_p2),32));
    tmp_7_fu_403_p2 <= std_logic_vector(unsigned(tmp_fu_235_p1) + unsigned(ap_const_lv31_7FFFFFFF));

    -- tmp_8_phi_fu_188_p6 assign process. --
    tmp_8_phi_fu_188_p6_assign_proc : process(sequence_no_V, ap_sig_cseq_ST_st1_fsm_0, tmp_cast_fu_243_p1, doRewind_in_V_read_read_fu_118_p2, tmp_4_fu_370_p2, tmp_s_fu_390_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and not((ap_const_lv1_0 = tmp_4_fu_370_p2)))) then 
            tmp_8_phi_fu_188_p6 <= tmp_s_fu_390_p2;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and not((ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (ap_const_lv3_1 = tmp_cast_fu_243_p1) and (ap_const_lv1_0 = doRewind_in_V_read_read_fu_118_p2) and (ap_const_lv1_0 = tmp_4_fu_370_p2)))) then 
            tmp_8_phi_fu_188_p6 <= sequence_no_V;
        else 
            tmp_8_phi_fu_188_p6 <= "XXX";
        end if; 
    end process;

    tmp_9_fu_341_p3 <= 
        tmp_1_fu_309_p2 when (sel_tmp2_fu_335_p2(0) = '1') else 
        sel_tmp_fu_321_p3;
    tmp_cast_fu_243_p1 <= std_logic_vector(resize(unsigned(curState),3));
    tmp_fu_235_p1 <= steps_count(31 - 1 downto 0);
    tmp_s_fu_390_p2 <= std_logic_vector(unsigned(sequence_no_V) + unsigned(tmp_13_v_cast_cast_fu_382_p3));
end behav;
